name: iban_formatter
description: You can use it to format IBANs
version: 0.0.2
homepage: https://github.com/NazmiCyln
repository: https://github.com/NazmiCyln/iban_formatter

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: